config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  get 'password_resets/index'
  post 'events/mark_event'

  resources :courses

  resources :events
  resources :blocks
  resources :user_sessions
  resources :users 
  resources :password_resets
  resources :ratings
  root :to => 'home#home'

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
post "csv_reader/import" # access to post for CSV-Reader.

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	validates_presence_of :family_name, :name
	belongs_to :user, :foreign_key => 'user_id'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profiles =Profile.all
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:family_name, :name, :birth_date, :bio, :user_id, :course_id, :course_name)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :family_name,"Name" %><br>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :name,"Vorname" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date,"Geburtsdatum" %><br>
    <%= f.date_select :birth_date, :start_year => getBirthDateStart(), :end_year => getBirthDateEnd() %>
  </div>
  <div class="field">
    <%= f.label :bio, "Über mich:" %><br>
    <%= f.text_area :bio %>
  </div>

  <%= form_for(@profile.user) do |f| %>
  <div class="field">
    <%= f.label :role%> <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %> 
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% end %>  
 <% end %>

app/views/profiles/edit.html.erb
<h1>Profil bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Profile</h1>

<table class = "table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vorname</th>
      <th>E-Mail</th>
      <th>Geburtsdatum</th>
      <th>Über mich</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.family_name %></td>
        <td><%= profile.name %></td>
        <td><%= profile.user.email %></td>
        <td><%= profile.birth_date %></td>
        <td><%= profile.bio %></td>
        <td><div class="btn-group btn-group-justified show_edit_del">
          <%= link_to 'Anzeigen', profile , class: 'btn btn-default'%>
          <%= link_to 'Bearbeiten', edit_profile_path(profile) , class: 'btn btn-default'%>
          <%= link_to 'Löschen', profile, method: :delete, data: { confirm: 'Sicher?' } , class: 'btn btn-default'%> 
        </div>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Profile', new_profile_path %> 

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @profile.family_name %>
</p>

<p>
  <strong>Vorname:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>E-Mail:</strong>
  <%= @profile.user.email %>
</p>

<p>
  <strong>Studiengang:</strong>
  <%= @profile.user.course.name %>
</p>

<p>
  <strong>Geburtsdatum:</strong>
  <%= @profile.birth_date %>
</p>

<p>
  <strong>Über mich:</strong>
  <%= @profile.bio %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %> 