config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  get 'password_resets/index'
  post 'events/mark_event'

  resources :courses

  resources :events
  resources :blocks
  resources :user_sessions
  resources :users 
  resources :password_resets
  resources :ratings
  root :to => 'home#home'

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
post "csv_reader/import" # access to post for CSV-Reader.

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  
  # set different User roles
  
  ROLES = %w[admin moderator student]

  # validates password and email
  validates :password, length: { minimum: 3 }, :on=>[:create, :update]
  validates :password, confirmation: true, :on=>[:create, :update]
  validates :password_confirmation, presence: true, :on=>[:create, :update]

  validates :email, presence: true, email: true, uniqueness: true
  
  has_many :ratings

  has_many :events_users
  has_many :events, through: :events_users

  has_one :profile, dependent: :destroy
  belongs_to :course

  accepts_nested_attributes_for :profile

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #cancancan authorizingController
  #load_and_authorize_resource
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params.except(:profiles))
    @user.profile = Profile.create(user_params[:profiles])
    respond_to do |format|
      if @user.save

        # Send email to user
        UserMailer.welcome_email(@user).deliver_now

        format.html { redirect_to @user.profile}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Benutzer wurde erfolgreich editiert.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Benutzer wurde erfolgreich gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :crypted_password,:password, :password_confirmation, :role, :course_id, profiles: [:name, :family_name])
    end
    
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class = "same_width1">
  <div class="field">
    <%= f.label :email, 'Email-Adresse eingeben' %><br/>
    <%= f.text_field :email, class: "same_width1_input" %>
  </div>

  <%= f.fields_for :profiles do |builder| %>

    <div class="field">
      <%= builder.label :name, 'Vorname' %>
      <%= builder.text_field :name, class: "same_width1_input" %>
    </div>

    <div class="field">
      <%= builder.label :family_name, 'Name' %>
      <%= builder.text_field :family_name, class: "same_width1_input" %>
    </div>
  <% end %>

  <div class="field">
   <%= f.label :course , 'Studiengang wählen' %><br />
   <%= f.collection_select :course_id, Course.order(:name), :id, :name, class: "same_width1_input" %>
  </div>


  <!-- virtual field, that will hold the password before it is encrypted into the database -->
  <div class="field">
   <%= f.label :password , 'Passwort wählen' %><br />
   <%= f.password_field :password,  class: "same_width1_input" %>
  </div>

  <div class="field">
   <%= f.label :password_confirmation, 'Passwort wiederholen'%><br />
   <%= f.password_field :password_confirmation, class: "same_width1_input" %>
  </div>  
  
  <div class="actions">
   <%= f.submit "Abschicken", class: "btn btn-success my_button1" %>  
  </div>
</div>
<% end %>

app/views/users/edit.html.erb
<h1>Nutzer bearbeiten</h1>

<div class="error">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="field">
    <%= f.label :email, 'Email-Adresse eingeben' %><br>
    <%= f.text_field :email %>
  </div>
 
  <!-- virtual field, that will hold the password before it is encrypted into the database -->
  <% if can? :edit, @user%>
     <div class="field">
       <%= f.label :password , 'Passwort wählen' %><br />
       <%= f.password_field :password %>
    </div>

    <div class="field">
       <%= f.label :password_confirmation, 'Passwort wiederholen'%><br />
       <%= f.password_field :password_confirmation %>
    </div>  
  <%end%>
  <% if can? :update, @user %>
     <div class="field">
       <%= f.label :role%> <%= f.collection_select(:role, User::ROLES, :to_s, lambda{|i| i.to_s.humanize}) %> 
     </div>
 <%end%>
 <div class="actions">
   <%= f.submit "Abschicken", class: "btn btn-success" %>  
  </div>
<% end %>

<%= link_to "Zurück", :back, class: "btn btn-default" %>
<!-- <button type="button" class="btn btn-lg btn-primary">Default</button> -->
<!--  <div class="btn-group">
  <%= link_to "Back", :back, class: "btn" %>
</div> -->

app/views/users/index.html.erb
<!--list of all users viewable for admin-->
<% if can? :manage, @user %>
<h1>Alle Nutzer</h1>

<!-- new table design for all the users -->
<table class="table table-striped">
  <thead>
    <tr>
      <th>Email</th>
      <th>Status</th>
      </tr>
  </thead>

<!-- list email of user and options/buttons to show profil, to change passwort and to delete profile -->
  <tbody>
    <% @users.each do |user| %>
      <tr> 
        <td><%= user.email %></td>
        <td><%= user.role %></td>
         <div class="btn-group btn-group-justified">       
          <%if user.profile != nil%>      
            <td class="col-sm-1"><%= link_to 'Anzeigen', profile_path(user.profile), class: 'btn btn-default'%></td>
<!-- Button No Profile ersetzen!!!--> 
          <%else%><td class="col-sm-1"><%= link_to 'No Profile',user, class: 'btn btn-default'%></td>
          <% end %>
          <%if user.id != current_user.id%>
            <td class="col-sm-2"><%= link_to 'Löschen', user, method: :delete, data: { confirm: 'Sicher?' } , class: 'btn btn-default'%></td>   
          <%end %>
        </div> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- is this important ? or maybe put to the top of the page? -->
<%= link_to 'Neuer Nutzer', new_user_path, class: 'btn btn-success'%>
<% end %>

<!-- not authorized redirected root path-->
<% if cannot? :manage, @user %>
    <%= not_authorized("Keine Rechte um User Übersicht aufzurufen") %>
<% end %>


 

app/views/users/new.html.erb
<h1>Neuer Nutzer</h1>

<%= render 'form' %>

<%= link_to "Zurück", :back, class: "btn btn-default" %>

app/views/users/show.html.erb
<%= redirect_to_profile %>