config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  get 'password_resets/index'
  post 'events/mark_event'

  resources :courses

  resources :events
  resources :blocks
  resources :user_sessions
  resources :users 
  resources :password_resets
  resources :ratings
  root :to => 'home#home'

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout
post "csv_reader/import" # access to post for CSV-Reader.

end

app/models/block.rb
class Block < ActiveRecord::Base
 validates_presence_of :name, :events
 validates :credits_min, :numericality => { :greater_than_or_equal_to => 0 }
 has_and_belongs_to_many :events
 has_and_belongs_to_many :courses
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  # GET /blocks.json
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  # GET /blocks/1.json
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  # POST /blocks.json
  def create
    @block = Block.new(block_params)

    respond_to do |format|
      if @block.save
        format.html { redirect_to @block, notice: 'Block was successfully created.' }
        format.json { render :show, status: :created, location: @block }
      else
        format.html { render :new }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blocks/1
  # PATCH/PUT /blocks/1.json
  def update
    respond_to do |format|
      if @block.update(block_params)
        format.html { redirect_to @block, notice: 'Block was successfully updated.' }
        format.json { render :show, status: :ok, location: @block }
      else
        format.html { render :edit }
        format.json { render json: @block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blocks/1
  # DELETE /blocks/1.json
  def destroy
    @block.destroy
    respond_to do |format|
      format.html { redirect_to blocks_url, notice: 'Block was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_params
      params.require(:block).permit(:name, :credits_min, :event_ids => [])
    end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<div class="error">
<%= form_for(@block) do |f| %>
  <% if @block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% @block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="field">
    <%= f.label :name, 'Name' %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :credits_min, 'Zu erreichende Credits' %><br>
    <%= f.number_field :credits_min %>
  </div>
  <div class="field">
    <%= f.label :event_ids, 'Veranstaltungen' %><br>
    <%= f.collection_check_boxes :event_ids, Event.all, :id, :title, {selected: @block.event_ids}, {multiple: true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Block bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Blöcke</h1>

<!-- changed layout of table -->
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Zu erreichende Credits</th>
      <th>Veranstaltungen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<!-- changed links to buttons -->
  <tbody>
    <% @blocks.order("name").each do |block| %>
      <tr>
        <td><%= block.name %></td>
        <td><%= block.credits_min %></td>
        <td><%= block.events.map { |a| a.title }.join("<br>").html_safe %></td>
        <div class="btn-group btn-group-justified">
          <td class="col-sm-1"><%= link_to 'Anzeigen', block , class: 'btn btn-default'%></td>
          <% if can? :edit, @blocks %>
          <td class="col-sm-1"><%= link_to 'Bearbeiten', edit_block_path(block) , class: 'btn btn-default'%></td>
          <% end%>
          <% if can? :destroy, @event %>
          <td class="col-sm-2"><%= link_to 'Löschen', block, method: :delete, data: { confirm: 'Sicher?' } , class: 'btn btn-default'%></td>
          <% end%>
          </div>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Block', new_block_path %>

app/views/blocks/new.html.erb
<h1>Neuer Block</h1>

<%= render 'form' %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @block.name %>
</p>
<p>
  <strong>Zu erreichende Credits:</strong>
  <%= @block.credits_min %>
</p>
<p>
  <strong>Veranstaltungen:<br></strong>
  <%= @block.events.map { |a| a.title }.join("<br>").html_safe %>
</p>

<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', :back %>